// VendingMachine.UI.ReactJs/src/pages/register/registerPage.tsx
import React, { Component } from 'react';
import { Form, FormikProps, Field, withFormik, ErrorMessage } from 'formik';

class RegisterPage extends Component<any, any> {

    getYear = () => {
        return new Date().getFullYear();
    };

    render() {
        return (
            <Form className="form-signin">
                <h1 className="h3 mb-3 font-weight-normal">New User Registration</h1>

                <label htmlFor="email" className="sr-only">Email address</label>
                <Field
                    name="email"
                    placeholder="Email address"
                    component="input"
                    type="text"
                    required
                    autoFocus
                />
                <ErrorMessage name="email" />

                <label htmlFor="password" className="sr-only">Password</label>
                <Field
                    name="password"
                    placeholder="Password"
                    component="input"
                    type="password"
                    required
                    autoFocus
                />
                <ErrorMessage name="password" />

                {/* <span *ngIf="(emailField.dirty || emailField.touched) && emailField.invalid && emailField.hasError('required')">
                    Email is required.
                </span>
                <span *ngIf="(emailField.dirty || emailField.touched) && emailField.invalid && emailField.hasError('email')">
                    Value has to be a valid email address.
                </span>
                <br />
                <span *ngIf="(passwordField.dirty || passwordField.touched) && passwordField.invalid && passwordField.hasError('required')">
                    Password is required.
                </span>
                <span *ngIf="(passwordField.dirty || passwordField.touched) && passwordField.invalid && passwordField.hasError('minlength')">
                    Password must be at least 4 characters long.
                </span> */}

                {/*<div className="mt-3">
                    <a (click)="register()">Register</a>
                </div> */}

                <button className="btn btn-lg btn-primary btn-block mt-2" type="submit">Sign in</button>
                <p className="mt-5 mb-3 text-muted">&copy; 2018-{ this.getYear() }</p>
            </Form>
        )
    }
}

export default RegisterPage;

// VendingMachine.UI.Angular/src/app/components/register-page/register-page.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { AuthService } from 'src/app/services/auth.service';
import { ILogin } from 'src/app/models/login';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register-page',
  templateUrl: './register-page.component.html',
  styleUrls: ['./register-page.component.css'],
})
export class RegisterPageComponent implements OnInit {
  registerForm: FormGroup;
  returnUrl: string;
  message = '';

  constructor(
    private formBuilder: FormBuilder,
    private router: Router,
    private authService: AuthService
  ) {
    this.registerForm = this.formBuilder.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(4)]],
    });
    this.returnUrl = '/home-page';
    this.authService.logout();
  }

  ngOnInit() {}

  // convenience getter for easy access to form fields
  get emailField() {
    return this.registerForm.get('email');
  }
  get passwordField() {
    return this.registerForm.get('password');
  }

  public register() {
    // stop here if form is invalid
    if (this.registerForm.invalid) {
      return;
    } else {
      const model: ILogin = {
        email: this.emailField?.value,
        password: this.passwordField?.value,
      };
      this.authService.registerUser(model).subscribe(
        (response) => {
          this.message = response.message;
        },
        (err: any) => {
          this.message = 'Register problem';
        }
      );
    }
  }

  public backToLogin() {
    this.router.navigate(['/login']);
  }
}

<div class="text-center">
    <img class="m-4" src="../../assets/logo-vm.png" alt="" height="50" />
</div>

<form class="form-register" [formGroup]="registerForm" (ngSubmit)="register()">    
    <h1 class="h3 mb-3 font-weight-normal">New User Registration</h1>
    <p *ngIf="message" class="text-center error alert alert-danger">{{message}}</p>
    <label for="inputEmail" class="sr-only">Email address</label>
    <input type="text" id="inputEmail" class="form-control" formControlName="email" placeholder="Email" autofocus />
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" class="form-control" formControlName="password" placeholder="Password" />

    <span *ngIf="(emailField.dirty || emailField.touched) && emailField.invalid && emailField.hasError('required')">
        Email is required.
      </span>
    <span *ngIf="(emailField.dirty || emailField.touched) && emailField.invalid && emailField.hasError('email')">
        Value has to be a valid email address.
    </span>
    <br />
    <span *ngIf="(passwordField.dirty || passwordField.touched) && passwordField.invalid && passwordField.hasError('required')">
        Password is required.
    </span>
    <span *ngIf="(passwordField.dirty || passwordField.touched) && passwordField.invalid && passwordField.hasError('minlength')">
        Password must be at least 4 characters long.
    </span>

    <button class="btn btn-lg btn-primary btn-block mt-2" type="submit" [disabled]="registerForm.invalid">Register</button>

    <div class="mt-3">
        <a routerLink="" (click)="backToLogin()">Back to Login</a>
    </div>
    
    <p class="mt-5 mb-3 text-muted">&copy; 2018-2019</p>
</form>
